baseURL: https://minajia.netlify.app/
languageCode: en-us
title: Portfolio website for Mina Jia
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
   # subtitle: |-
  #    A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
  #    AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, Welcome to Mina's Page
  blog: {}
  contact: 
    address:
      - city: Shenzhen, 518000
        country: China
        street: Nanshan Distrinct
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mjia.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (086) 8866-6688 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Mina 
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/mina_jiaqiyuan/
      - icon: fa-github
        label: GitHub
        url: https://github.com/QiyuanJia-0928/
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/qiyuan-mina-jia
  image: ''
  name: Mina Jia
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#       url: elements.html 
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: LBS2.jpg
        subtitle: Draw closer and see behind the walls
        title: My Career Journey So Far
        url: blogs/cv
      - image: Wharton.jpg
        subtitle: See the world and see myself
        title: My Life Journey So Far
        url: blogs/life
      - image: Unimelb.jpg
        subtitle: Lorem Etiam Nullam
        title: Unimelb
        url: blogs/magna
      - image: Mina.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "This page is dedicated to sharing some of my life and my work on data analysis and I hope you would enjoy exploring the site" 
    title: Background
    url: blogs
